#delimit ;
capture log close ;
capture clear all ;
set more off ;


global dct_directory "C:\Users\wodtke\Desktop\projects\nhood_mediation_toxins\programs\_DCT\" ;
global data_directory "C:\Users\wodtke\Desktop\projects\nhood_mediation_toxins\data\eclsb\" ;
global log_directory "C:\Users\wodtke\Desktop\projects\nhood_mediation_toxins\programs\_LOGS\" ;

log using "${log_directory}01_create_v01_eclsb.log", replace ;


/******************************************************************
PROGRAM NAME: 01_create_v01_eclsb.do
AUTHOR: KW, GW
PURPOSE: Read in raw data from ecls extraction tool to stata
*******************************************************************/

/********************************
READ IN RAW DATA USING DICTIONARY
*********************************/
infile using "${dct_directory}eclsb_data_extract_2021_03_19.dct" ;

keep if  (Y1CHRACE == 1 | 
       Y1CHRACE == 2 | 
       Y1CHRACE == 3 | 
       Y1CHRACE == 4 | 
       Y1CHRACE == 5 | 
       Y1CHRACE == 6 | 
       Y1CHRACE == 7 | 
       Y1CHRACE == 8 | 
       Y1CHRACE == -9) & 
      (XKWHENK == 1 | 
       XKWHENK == 2 | 
       XKWHENK == 3 | 
       XKWHENK == 4 | 
       XKWHENK == 5 | 
       XKWHENK == 6 | 
       XKWHENK == 7 | 
       XKWHENK == 8 | 
       XKWHENK == 9 | 
       XKWHENK == 99 | 
       XKWHENK == .) & 
      (X1BTHWGT == 1 | 
       X1BTHWGT == 2 | 
       X1BTHWGT == 3 | 
       X1BTHWGT == -9) & 
      (X4GRDLVL == 0 | 
       X4GRDLVL == 1 | 
       X4GRDLVL == 2 | 
       X4GRDLVL == 3 | 
       X4GRDLVL == 4 | 
       X4GRDLVL == -9 | 
       X4GRDLVL == .) & 
      (X5GRDLVL == 0 | 
       X5GRDLVL == 1 | 
       X5GRDLVL == 2 | 
       X5GRDLVL == 3 | 
       X5GRDLVL == 4 | 
       X5GRDLVL == .) & 
      (X5RPTR == 1 | 
       X5RPTR == 2 | 
       X5RPTR == 3 | 
       X5RPTR == -1 | 
       X5RPTR == .);
   label define V0021_
      1 "NOT AT ALL"
      2 "ONCE OR TWICE"
      3 "3 TO 6 TIMES"
      4 "EVERY DAY"
      -9 "NOT ASCERTAINED"
   ;
   label define V0027_
      1 "YES"
      2 "NO"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0031_
      1 "NOT YET"
      2 "SOMETIMES"
      3 "OFTEN"
      -8 "DON'T KNOW"
   ;
   label define V0066_
      1 "MORE THAN ONCE A DAY"
      2 "ABOUT ONCE A DAY"
      3 "A FEW TIMES A WEEK"
      4 "A FEW TIMES A MONTH"
      5 "RARELY"
      6 "NOT AT ALL"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0072_
      1 "EXCELLENT"
      2 "VERY GOOD"
      3 "GOOD"
      4 "FAIR"
      5 "POOR"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0075_
      1 "OWN YOUR OWN HOME"
      2 "RENT YOUR HOUSE OR APARTMENT"
      3 "EXCHANGE SERVICES FOR HOUSING"
      4 "LIVE WITH FRIENDS OR RELATIVES AND PAY PART OF THE EXPENSES"
      5 "LIVE WITH FRIENDS OR RELATIVES AND NOT PAY FOR HOUSING"
      6 "LIVE IN TEMPORARY HOUSING OR A SHELTER"
      7 "NOT PAY FOR HOUSING AS PART OF A JOB (E.G. MILITARY, CLERGY)"
      91 "HAVE ANOTHER TYPE OF HOUSING ARRANGEMENT (SPECIFY)"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0076_
      1 "A HOUSE OR TOWNHOUSE"
      2 "AN APARTMENT OR CONDOMINIUM"
      3 "A MOBILE HOME OR TRAILER"
      4 "A COMMUNITY SHELTER"
      5 "A HOTEL OR MOTEL ROOM"
      6 "ARE YOU HOMELESS"
      91 "DO YOU LIVE IN ANOTHER TYPE OF HOUSING (SPECIFY)"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0083_
      0 "ENGLISH"
      1 "ARABIC"
      2 "CHINESE"
      3 "FILIPINO"
      4 "FRENCH"
      5 "GERMAN"
      6 "GREEK"
      7 "ITALIAN"
      8 "JAPANESE"
      9 "KOREAN"
      10 "POLISH"
      11 "PORTUGUESE"
      12 "SPANISH"
      13 "VIETNAMESE"
      14 "AFRICAN"
      15 "EAST EUROPEAN"
      16 "NATIVE AMERICAN"
      17 "SIGN LANGUAGE"
      18 "MIDDLE EASTERN"
      19 "WEST EUROPEAN"
      20 "INDIAN SUBCONTINENT"
      21 "SOUTHEAST ASIAN"
      22 "PACIFIC ISLAND"
      23 "CANNOT CHOOSE"
      91 "SOME OTHER LANGUAGE (SPECIFY)"
   ;
   label define V0089_
      1 "MARRIED"
      2 "SEPARATED"
      3 "DIVORCED"
      4 "WIDOWED"
      5 "HAVE YOU NEVER BEEN MARRIED"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0119_
      1 "3 OR MORE INTENSE/HEIGHTENED/PROLONGED DISPLAYS-NEG AFFECT"
      2 "ONE OR TWO INTENSE/HEIGHTENED/PROLONGED DISPLAYS- NEG AFFECT"
      3 "THREE OR MORE BRIEF DISPLAYS OF NEGATIVE AFFECT"
      4 "ONE OR TWO BRIEF DISPLAYS OF NEGATIVE AFFECT"
      5 "NO NEGATIVE AFFECT DISPLAYED"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0120_
      1 "NO POSITIVE AFFECT DISPLAYED"
      2 "ONE OR TWO BRIEF DISPLAYS OF POSITIVE AFFECT"
      3 "THREE OR MORE BRIEF DISPLAYS OF POSITIVE AFFECT"
      4 "ONE OR TWO INTENSE/HEIGHTENED/PROLONGED DISPLAYS- POS AFFECT"
      5 "3 OR MORE INTENSE/HEIGHTENED/PROLONGED DISPLAYS-POS AFFECT"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0121_
      1 "NO ATTEMPTS TO INTERACT SOCIALLY"
      2 "ONE OR TWO ATTEMPTS TO INTERACT SOCIALLY"
      3 "SEVERAL ATTEMPTS TO INTERACT SOCIALLY"
      4 "MANY ATTEMPTS TO INTERACT SOCIALLY"
      5 "CONSTANT ATTEMPTS TO INTERACT SOCIALLY"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0123_
      1 "CONSTANTLY OFF TASKS - DOES NOT ATTEND"
      2 "TYPICALLY OFF TASK - ATTENDS IN ONE OR TWO INSTANCES"
      3 "OFF TASK HALF THE TIME"
      4 "TYPICALLY ATTENDS -ATTENTION WANDERS IN ONE OR TWO INSTANCES"
      5 "CONSTANTLY ATTENDS"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0258_
      1 "YES, COMPLETE"
      2 "NO, SAQ NOT ADMINISTERED BECAUSE NO REGULAR CARE"
      3 "NO, SAQ NOT ADMIN-CCO NOT COMP-REASON OTHER THAN NO REG CARE"
      4 "NO, CCO COMPLETED, NOT ELIGIBLE FOR CDSAQ-HOME BASED OBSRVTN"
      5 "NO, COMPLETED CENTER-BASED OBSERVATION, SAQ REFUSAL"
      6 "NO, CTR-BSD OBS COMPLT, OTH NRSP-OTH NRSP, SAQ NEVER RCPTD"
      81 "NO, CASE NOT SELECTED - CASE FROM ALASKA / HAWAII"
      82 "NO, CASE NOT SELECTED - SPECIAL AMERICAN INDIAN SAMPLE CASE"
      83 "NO, CASE NOT SELECTED - PROBABILITY OF SELECTION"
   ;
   label define V0259_
      1 "YES, COMPLETED"
      2 "NO, NOT COMPLETED"
      3 "COMPLETED, DATA NOT USEABLE"
   ;
   label define V0260_
      0 "NO TWO BAGS TAPE"
      1 "TWO BAGS TAPE CODED"
      2 "NO, TWO BAGS TAPE NOT CODEABLE"
   ;
   label define V0262_
      1 "YES"
      2 "NO"
      -1 "NOT ELIGIBLE FOR RESIDENT FATHER SAQ"
   ;
   label define V0268_
      1 "TYPE A, AVOIDANT"
      2 "TYPE B, SECURE"
      3 "TYPE C, AMBIVALENT"
      4 "TYPE D, DISORGANIZED"
      -9 "NOT ASCERTAINED"
   ;
   label define V0270_
      1 "YES"
      2 "NO, REFUSAL/INCOMPLETE BY NONRESIDENT FATHER"
      3 "NO, NONRESIDENT FATHER PRESENT BUT NO MOTHER PERMISSION"
      4 "NO, NONRESIDENT FATHER INELIGIBLE-LACK OF CONTACT WITH CHILD"
      5 "NO, BECAUSE NO NONRESIDENT FATHER"
      6 "NO, RESP IS NOT BIO MOM, DO NOT ASK ABOUT NONRESIDENT FATHER"
   ;
   label define V0271_
      1 "YES, COMPLETE"
      2 "NO, NO REGULAR CHILD CARE REPORTED"
      3 "NO, PARENT DID NOT SIGN CONSENT FORM"
      4 "NO, NOT FIELDED, CARE NOT LEGITIMATE (E.G., MOM AS PROVIDER)"
      5 "NO, NOT FIELDED FOR TELEPHONE INTERVIEW, UNKNOWN ELIGIBILITY"
      6 "NO, FIELDED FOR TEL INTERVIEW, BUT INELIGIBLE (CARE CHANGE)"
      7 "NO, REFUSED TELEPHONE INTERVIEW"
      8 "NO, FIELDED FOR TELEPHONE INTERVIEW, BUT OTHER NONRESPONSE"
   ;
   label define V0275_
      1 "35 HOURS OR MORE PER WEEK"
      2 "LESS THAN 35 HOURS PER WEEK"
      3 "LOOKING FOR WORK"
      4 "NOT IN THE LABOR FORCE"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0276_
      1 "$5,000 OR LESS"
      2 "$5,001 TO $10,000"
      3 "$10,001 TO $15,000"
      4 "$15,001 TO $20,000"
      5 "$20,001 TO $25,000"
      6 "$25,001 TO $30,000"
      7 "$30,001 TO $35,000"
      8 "$35,001 TO $40,000"
      9 "$40,001 TO $50,000"
      10 "$50,001 TO $75,000"
      11 "$75,001 TO $100,000"
      12 "$100,001 TO $200,000"
      13 "$200,001 OR MORE"
   ;
   label define V0279_
      1 "8TH GRADE OR BELOW"
      2 "9TH TO 12TH GRADES"
      3 "HIGH SCHOOL DIPLOMA/EQUIVALENT"
      4 "VOC/TECH PROGRAM"
      5 "SOME COLLEGE"
      6 "BACHELOR'S DEGREE"
      7 "GRADUATE PROFESSIONAL SCHOOL/NO DEGREE"
      8 "MASTER'S DEGREE (MA/MS)"
      9 "DOCTORATE OR PROFESSIONAL DEGREE"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0282_
      1 "BIOLOGICAL MOTHER AND BIOLOGICAL FATHER"
      2 "BIOLOGICAL MOTHER AND OTHER FATHER"
      3 "BIOLOGICAL FATHER AND OTHER MOTHER"
      4 "BIOLOGICAL MOTHER ONLY"
      5 "BIOLOGICAL FATHER ONLY"
      6 "TWO ADOPTIVE PARENTS"
      7 "SINGLE ADOPTIVE PARENT OR ADOPTIVE AND STEP PARENT"
      8 "RELATED GUARDIAN(S)"
      9 "UNRELATED GUARDIAN(S)"
      10 "BIOLOGICAL MOTHER AND OTHER MOTHER"
   ;
   label define V0283_
      1 "BIRTH FATHER"
      2 "ADOPTIVE FATHER"
      3 "STEP FATHER"
      4 "FOSTER FATHER"
      5 "REL/NONREL RESP-FATHER FIG"
      6 "MOTHER'S PARTNER-FATHER FIG"
      7 "REL/NONREL RESPS PARTNER-FATHER FIG"
      8 "FATHER-UNKNOWN TYPE"
      9 "NO RESIDENT FATHER"
   ;
   label define V0284_
      1 "BIRTH MOTHER"
      2 "ADOPTIVE MOTHER"
      3 "STEP MOTHER"
      4 "FOSTER MOTHER"
      5 "REL/NONREL RESP-MOTHER FIG"
      6 "FATHER'S PARTNER-MOTHER FIG"
      7 "REL/NONREL RESPS PARTNER-MOTHER FIG"
      8 "MOTHER-UNKNOWN TYPE"
      9 "NO RESIDENT MOTHER"
   ;
   label define V0286_
      1 "BSF-R MENTAL ADMINISTERED, NO MODIFICATIONS"
      2 "BSF-R MENTAL ADMINISTERED, WITH MODIFICATIONS"
      3 "BSF-R MENTAL ADMINISTERED, UNKNOWN MODIFICATION STATUS"
      4 "NOT SCOREABLE"
      5 "NOT ADMINISTERED"
   ;
   label define V0287_
      1 "BSF-R MOTOR ADMINISTERED, NO MODIFICATIONS"
      2 "BSF-R MOTOR ADMINISTERED, WITH MODIFICATIONS"
      3 "BSF-R MOTOR ADMINISTERED, UNKNOWN MODIFICATION STATUS"
      4 "NOT SCOREABLE"
      5 "NOT ADMINISTERED"
   ;
   label define V0289_
      1 "FIRST QUINTILE (LOWEST)"
      2 "SECOND QUINTILE"
      3 "THIRD QUINTILE"
      4 "FOURTH QUINTILE"
      5 "FIFTH QUINTILE (HIGHEST)"
   ;
   label define V0292_
      1 "MANAGEMENT OCCUPATION"
      2 "BUSINESS AND FINANCIAL OPERATIONS OCCUPATIONS"
      3 "COMPUTER AND MATHEMATICAL OCCUPATIONS"
      4 "ARCHITECTURE AND ENGINEERING"
      5 "LIFE,PHYSICAL AND SOCIAL SCIENCE"
      6 "COMMUNITY AND SOCIAL SERVICE"
      7 "LEGAL"
      8 "EDUCATION,TRAINING AND LIBRARY OCCUPATIONS"
      9 "ARTS,DESIGN,ENTERTAINMENT,SPORTS AND MEDIA"
      10 "HEALTHCARE PRACTITIONER AND TECHNICAL"
      11 "HEALTHCARE SUPPORT"
      12 "PROTECTIVE SERVICE"
      13 "FOOD PREPARATION AND SERVING RELATED"
      14 "BUILDING AND GROUNDS CLEANING AND MAINTENANCE"
      15 "PERSONAL CARE AND SERVICES"
      16 "SALES AND RELATED OCCUPATIONS"
      17 "OFFICE AND ADMINISTRATIVE SUPPORT"
      18 "FARMING,FISHING AND FORESTRY"
      19 "CONSTRUCTION AND EXTRACTION OCCUPATIONS"
      20 "INSTALLATION,MAINTENANCE AND REPAIR"
      21 "PRODUCTION"
      22 "TRANSPORTATION AND MATERIAL MOVING OCCUPATIONS"
      23 "MILITARY SPECIFIC OCCUPATIONS"
      90 "NOT IN THE LABOR FORCE (RETIRED, DISABLED, UNCLASSIFIED)"
      99 "UNEMPLOYED, ACTIVELY LOOKING FOR WORK"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0293_
      1 "MARRIED"
      2 "SEPARATED"
      3 "DIVORCED"
      4 "WIDOWED"
      5 "NEVER MARRIED"
      6 "NON BIO OR ADOPTIVE PARENTS"
      -9 "NOT ASCERTAINED"
   ;
   label define V0294_
      0 "NO NONPARENTAL CARE"
      1 "RELATIVE CARE IN CHILD'S HOME"
      2 "RELATIVE CARE IN ANOTHER HOME"
      3 "RELATIVE CARE, LOCATION VARIES"
      4 "NONRELATIVE CARE IN CHILD'S HOME"
      5 "NONRELATIVE CARE IN ANOTHER HOME"
      6 "NONRELATIVE CARE, LOCATION VARIES"
      7 "CENTER-BASED PROGRAM"
      8 "MULTIPLE CARE ARRANGEMENTS WITH SAME HOURS IN EACH"
      -9 "NOT ASCERTAINED"
   ;
   label define V0295_
      1 "NON-ENGLISH LANGUAGE"
      2 "ENGLISH LANGUAGE"
   ;
   label define V0296_
      1 "NORTHEAST"
      2 "MIDWEST"
      3 "SOUTH"
      4 "WEST"
   ;
   label define V0297_
      0 "NOT IMPUTED"
      1 "IMPUTED"
   ;
   label define V0299_
      1 "WHITE, NON-HISPANIC"
      2 "BLACK OR AFRICAN AMERICAN, NON-HISPANIC"
      3 "HISPANIC, RACE SPECIFIED"
      4 "HISPANIC, NO RACE SPECIFIED"
      5 "ASIAN, NON-HISPANIC"
      6 "NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER, NON-HISPANIC"
      7 "AMERICAN INDIAN OR ALASKA NATIVE, NON-HISPANIC"
      8 "MORE THAN 1 RACE, NON-HISPANIC"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0302_
      1 "YES"
      2 "NO"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0306_
      1 "URBAN, INSIDE UA"
      2 "URBAN, INSIDE UC"
      3 "RURAL"
   ;
   label define V0309_
      1 "YES, COMPLETE"
      2 "NO, NO REGULAR CHILD CARE REPORTED"
      3 "NO, NOT SELECTED, NO ARRANGEMENT = OR > 10 HOURS PER WEEK"
      4 "NO, SELECTED FOR CCO BUT PARENT DID NOT SIGN CONSENT FORM"
      5 "NO, SELECTED FOR CCO BUT CCP NOT COMPLETED IN ENTIRETY"
      6 "NO, SELECTED FOR CCO, CCP COMPLETE, REFUSED CCO IN THE CCP"
      7 "NO, NOT FIELDED FOR CCO, LANG OTHER THAN ENGLISH OR SPANISH"
      8 "NO, FIELDED FOR CCO BUT PROVIDER NOT ELIGIBLE"
      9 "NO, FIELDED FOR CCO BUT PROVIDER NO LONGER CARING FOR CHILD"
      10 "NO, CCO REFUSAL"
      11 "NO, CCO OTH NRSP(TOO FAR/LNG PRB/NONLOC/STPPD WRK/NOT RCPTD)"
      81 "NO, CASE WAS NOT SELECTED BECAUSE CASE WAS FRM ALASKA/HAWAII"
      82 "NO, CASE NOT SELECTED-CASE FROM SPECIAL AMER. INDIAN SAMPLE"
      83 "NO, REG CH CARE NOT SELECTED BASED ON SMPL SLCTN PROB"
   ;
   label define V0312_
      0 "NO INFORMATION ON ADEQUACY OF PRENATAL CARE"
      1 "INADEQUATE"
      2 "INTERMEDIATE"
      3 "ADEQUATE"
      4 "ADEQUATE PLUS"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0313_
      1 "BC BIRTH WEIGHT < 750 GRAMS"
      2 "BC BIRTH WEIGHT => 750 AND < 1000 GRAMS"
      3 "BC BIRTH WEIGHT => 1000 AND < 1250 GRAMS"
      4 "BC BIRTH WEIGHT => 1250 AND < 1500 GRAMS"
      5 "BC BIRTH WEIGHT => 1500 AND < 1750 GRAMS"
      6 "BC BIRTH WEIGHT => 1750 AND < 2000 GRAMS"
      7 "BC BIRTH WEIGHT => 2000 AND < 2250 GRAMS"
      8 "BC BIRTH WEIGHT => 2250 AND < 2500 GRAMS"
      9 "BC BIRTH WEIGHT => 2500 AND < 2750 GRAMS"
      10 "BC BIRTH WEIGHT => 2750 AND < 3000 GRAMS"
      11 "BC BIRTH WEIGHT => 3000 AND < 3250 GRAMS"
      12 "BC BIRTH WEIGHT => 3250 AND < 3500 GRAMS"
      13 "BC BIRTH WEIGHT => 3500 AND < 3750 GRAMS"
      14 "BC BIRTH WEIGHT => 3750 AND < 4000 GRAMS"
      15 "BC BIRTH WEIGHT =>4000 AND < 4250 GRAMS"
      16 "BC BIRTH WEIGHT =>4250 AND < 4500 GRAMS"
      17 "BC BIRTH WEIGHT => 4500 GRAMS"
   ;
   label define V0317_
      95 "CHILD HAS NOT DONE YET"
      -7 "REFUSED"
      -8 "DON'T KNOW"
   ;
   label define V0327_
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0342_
      1 "ALABAMA"
      2 "ALASKA"
      4 "ARIZONA"
      5 "ARKANSAS"
      6 "CALIFORNIA"
      8 "COLORADO"
      9 "CONNECTICUT"
      10 "DELAWARE"
      11 "DISTRICT OF COLUMBIA"
      12 "FLORIDA"
      13 "GEORGIA"
      15 "HAWAII"
      16 "IDAHO"
      17 "ILLINOIS"
      18 "INDIANA"
      19 "IOWA"
      20 "KANSAS"
      21 "KENTUCKY"
      22 "LOUISIANA"
      23 "MAINE"
      24 "MARYLAND"
      25 "MASSACHUSETTS"
      26 "MICHIGAN"
      27 "MINNESOTA"
      28 "MISSISSIPPI"
      29 "MISSOURI"
      30 "MONTANA"
      31 "NEBRASKA"
      32 "NEVADA"
      33 "NEW HAMPSHIRE"
      34 "NEW JERSEY"
      35 "NEW MEXICO"
      36 "NEW YORK"
      37 "NORTH CAROLINA"
      38 "NORTH DAKOTA"
      39 "OHIO"
      40 "OKLAHOMA"
      41 "OREGON"
      42 "PENNSYLVANIA"
      44 "RHODE ISLAND"
      45 "SOUTH CAROLINA"
      46 "SOUTH DAKOTA"
      47 "TENNESSEE"
      48 "TEXAS"
      49 "UTAH"
      50 "VERMONT"
      51 "VIRGINIA"
      53 "WASHINGTON"
      54 "WEST VIRGINIA"
      55 "WISCONSIN"
      56 "WYOMING"
      60 "AMERICAN SAMOA"
      66 "GUAM"
      69 "NORTHERN MARIANAS"
      72 "PUERTO RICO"
      78 "VIRGIN ISLANDS"
      -6 "FOREIGN RESIDENTS"
   ;
   label define V0345_
      1 "BIOLOGICAL MOTHER AND BIOLOGICAL FATHER"
      2 "BIOLOGICAL MOTHER AND OTHER FATHER"
      3 "BIOLOGICAL FATHER AND OTHER MOTHER"
      4 "BIOLOGICAL MOTHER ONLY"
      5 "BIOLOGICAL FATHER ONLY"
      6 "TWO ADOPTIVE PARENTS"
      7 "SINGLE ADOPTIVE PARENT OR ADOPTIVE AND STEP PARENT"
      8 "RELATED GUARDIAN(S)"
      9 "UNRELATED GUARDIAN(S)"
   ;
   label define V0346_
      1 "MARRIED"
      2 "SEPARATED"
      3 "DIVORCED"
      4 "WIDOWED"
      5 "NEVER MARRIED"
      6 "RESPONDENT IS NOT BIOLOGICAL OR ADOPTIVE PARENT"
      -9 "NOT ASCERTAINED"
   ;
   label define V0347_
      1 "$5,000 OR LESS"
      2 "$5,001 TO $10,000"
      3 "$10,001 TO $15,000"
      4 "$15,001 TO $20,000"
      5 "$20,001 TO $25,000"
      6 "$25,001 TO $30,000"
      7 "$30,001 TO $35,000"
      8 "$35,001 TO $40,000"
      9 "$40,001 TO $50,000"
      10 "$50,001 TO $75,000"
      11 "$75,001 TO $100,000"
      12 "$100,001 TO $200,000"
      13 "$200,001 OR MORE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0348_
      1 "BIRTH FATHER"
      2 "ADOPTIVE FATHER"
      3 "STEP FATHER"
      4 "FOSTER FATHER"
      5 "REL/NONREL RESP - FATHER FIGURE"
      6 "MOTHER'S PARTNER - FATHER FIGURE"
      7 "REL/NONREL RESPS PARTNER - FATHER FIGURE"
      8 "FATHER, UNKNOWN TYPE"
      9 "NO RESIDENT FATHER"
   ;
   label define V0349_
      1 "WHITE, NON-HISPANIC"
      2 "BLACK OR AFRICAN AMERICAN, NON-HISPANIC"
      3 "HISPANIC, RACE SPECIFIED"
      4 "HISPANIC, NO RACE SPECIFIED"
      5 "ASIAN, NON-HISPANIC"
      6 "NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER, NON-HISPANIC"
      7 "AMERICAN INDIAN OR ALASKA NATIVE, NON-HISPANIC"
      8 "MORE THAN 1 RACE, NON-HISPANIC"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0353_
      1 "8TH GRADE OR BELOW"
      2 "9TH TO 12TH GRADES"
      3 "HIGH SCHOOL DIPLOMA/EQUIVALENT"
      4 "VOC/TECH PROGRAM"
      5 "SOME COLLEGE"
      6 "BACHELOR'S DEGREE"
      7 "GRADUATE PROFESSIONAL SCHOOL/NO DEGREE"
      8 "MASTER'S DEGREE (MA/MS)"
      9 "DOCTORATE OR PROFESSIONAL DEGREE"
      -1 "NO NON-RESIDENT FATHER"
      -9 "NOT ASCERTAINED"
   ;
   label define V0354_
      1 "35 HOURS OR MORE PER WEEK"
      2 "LESS THAN 35 HOURS PER WEEK"
      3 "LOOKING FOR WORK"
      4 "NOT IN THE LABOR FORCE"
      -1 "NO RESIDENT FATHER"
      -9 "NOT ASCERTAINED"
   ;
   label define V0355_
      1 "MANAGEMENT OCCUPATION"
      2 "BUSINESS AND FINANCIAL OPERATIONS OCCUPATIONS"
      3 "COMPUTER AND MATHEMATICAL OCCUPATIONS"
      4 "ARCHITECTURE AND ENGINEERING"
      5 "LIFE, PHYSICAL AND SOCIAL SCIENCE"
      6 "COMMUNITY AND SOCIAL SERVICE"
      7 "LEGAL"
      8 "EDUCATION, TRAINING AND LIBRARY OCCUPATIONS"
      9 "ARTS, DESIGN, ENTERTAINMENT, SPORTS AND MEDIA"
      10 "HEALTHCARE PRACTITIONER AND TECHNICAL"
      11 "HEALTHCARE SUPPORT"
      12 "PROTECTIVE SERVICE"
      13 "FOOD PREPARATION AND SERVING RELATED"
      14 "BUILDING AND GROUNDS CLEANING AND MAINTENANCE"
      15 "PERSONAL CARE AND SERVICES"
      16 "SALES AND RELATED OCCUPATIONS"
      17 "OFFICE AND ADMINISTRATIVE SUPPORT"
      18 "FARMING,FISHING AND FORESTRY"
      19 "CONSTRUCTION AND EXTRACTION OCCUPATIONS"
      20 "INSTALLATION, MAINTENANCE AND REPAIR"
      21 "PRODUCTION"
      22 "TRANSPORTATION AND MATERIAL MOVING OCCUPATIONS"
      23 "MILITARY SPECIFIC OCCUPATIONS"
      90 "NOT IN THE LABOR FORCE (RETIRED, DISABLED, UNCLASSIFIED)"
      99 "UNEMPLOYED, ACTIVELY LOOKING FOR WORK"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0357_
      1 "BIRTH MOTHER"
      2 "ADOPTIVE MOTHER"
      3 "STEP MOTHER"
      4 "FOSTER MOTHER"
      5 "REL/NONREL RESP - MOTHER FIGURE"
      6 "FATHER'S PARTNER - MOTHER FIGURE"
      7 "REL/NONREL RESPS PARTNER - MOTHER FIGURE"
      8 "MOTHER, UNKNOWN TYPE"
      9 "NO RESIDENT MOTHER"
   ;
   label define V0358_
      1 "WHITE, NON-HISPANIC"
      2 "BLACK OR AFRICAN AMERICAN,NON-HISPANIC"
      3 "HISPANIC, RACE SPECIFIED"
      4 "HISPANIC, NO RACE SPECIFIED "
      5 "ASIAN, NON-HISPANIC"
      6 "NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER, NON-HISPANIC"
      7 "AMERICAN INDIAN OR ALASKA NATIVE, NON-HISPANIC"
      8 "MORE THAN 1 RACE, NON-HISPANIC"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0360_
      1 "35 HOURS OR MORE PER WEEK"
      2 "LESS THAN 35 HOURS PER WEEK"
      3 "LOOKING FOR WORK"
      4 "NOT IN THE LABOR FORCE"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0361_
      1 "MANAGEMENT OCCUPATION"
      2 "BUSINESS AND FINANCIAL OPERATIONS OCCUPATIONS"
      3 "COMPUTER AND MATHEMATICAL OCCUPATIONS"
      4 "ARCHITECTURE AND ENGINEERING"
      5 "LIFE, PHYSICAL AND SOCIAL SCIENCE"
      6 "COMMUNITY AND SOCIAL SERVICE"
      7 "LEGAL"
      8 "EDUCATION, TRAINING AND LIBRARY OCCUPATIONS"
      9 "ARTS, DESIGN, ENTERTAINMENT, SPORTS AND MEDIA"
      10 "HEALTHCARE PRACTITIONER AND TECHNICAL"
      11 "HEALTHCARE SUPPORT"
      12 "PROTECTIVE SERVICE"
      13 "FOOD PREPARATION AND SERVING RELATED"
      14 "BUILDING AND GROUNDS CLEANING AND MAINTENANCE"
      15 "PERSONAL CARE AND SERVICES"
      16 "SALES AND RELATED OCCUPATIONS"
      17 "OFFICE AND ADMINISTRATIVE SUPPORT"
      18 "FARMING, FISHING AND FORESTRY"
      19 "CONSTRUCTION AND EXTRACTION OCCUPATIONS"
      20 "INSTALLATION, MAINTENANCE AND REPAIR"
      21 "PRODUCTION"
      22 "TRANSPORTATION AND MATERIAL MOVING OCCUPATIONS"
      23 "MILITARY SPECIFIC OCCUPATIONS"
      90 "NOT IN THE LABOR FORCE (RETIRED, DISABLED, UNCLASSIFIED)"
      99 "UNEMPLOYED, ACTIVELY LOOKING FOR WORK"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0364_
      0 "NO NONPARENTAL CARE"
      1 "RELATIVE CARE IN CHILDS HOME"
      2 "RELATIVE CARE IN ANOTHER HOME"
      3 "RELATIVE CARE, LOCATION VARIES"
      4 "NONRELATIVE CARE IN CHILDS HOME"
      5 "NONRELATIVE CARE IN ANOTHER HOME"
      6 "NONRELATIVE CARE, LOCATION VARIES"
      7 "CENTER-BASED PROGRAM"
      8 "EQUAL TIME IN MULTIPLE ARRANGEMENTS"
      -9 "NOT ASCERTAINED"
   ;
   label define V0365_
      1 "WHITE, NON-HISPANIC"
      2 "BLACK OR AFRICAN AMERICAN,NON-HISPANIC"
      3 "HISPANIC, RACE SPECIFIED"
      4 "HISPANIC, NO RACE SPECIFIED"
      5 "ASIAN, NON-HISPANIC"
      6 "NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER, NON-HISPANIC"
      7 "AMERICAN INDIAN OR ALASKA NATIVE, NON-HISPANIC"
      8 "MORE THAN 1 RACE, NON-HISPANIC"
      -9 "NOT ASCERTAINED"
   ;
   label define V0367_
      1 "35 HOURS OR MORE PER WEEK"
      2 "LESS THAN 35 HOURS PER WEEK "
      3 "LOOKING FOR WORK"
      4 "NOT IN THE LABOR FORCE"
      -1 "NO NON-RESIDENT FATHER"
      -9 "NOT ASCERTAINED"
   ;
   label define V0368_
      1 "URBAN, INSIDE UA"
      2 "URBAN, INSIDE UC"
      3 "RURAL"
      -9 "NOT ASCERTAINED"
   ;
   label define V0369_
      1 "BSF-R MENTAL ADMINISTERED, NO MODIFICATIONS"
      2 "BSF-R MENTAL ADMINISTERED, WITH MODIFICATIONS"
      3 "BSF-R MENTAL ADMINISTERED, UNKNOWN MODIFICATION STATUS"
      4 "NOT SCOREABLE"
      5 "NOT ADMINISTERED"
   ;
   label define V0370_
      0 "NO NCATS TAPE"
      1 "NCATS TAPE CODED"
      2 "NCATS TAPE NOT CODED, FOREIGN LANGUAGE"
      3 "NCATS TAPE NOT CODED, UNCODEABLE"
   ;
   label define V0372_
      0 "NOT ELIGIBLE FOR RESIDENT FATHER SAQ"
      1 "YES"
      2 "NO"
   ;
   label define V0373_
      1 "YES"
      2 "NO, REFUSAL/INCOMPLETE BY NONRESIDENT FATHER"
      3 "NO, NONRESIDENT FATHER PRESENT BUT NO MOTHER PERMISSION"
      4 "NO, NONRESIDENT FATHER INELIGIBLE (LACK OF CONTACT)"
      5 "NO, BECAUSE NO NONRESIDENT FATHER"
      6 "NO, NOT ASKED, RESPONDENT NOT BIO-MOTHER"
   ;
   label define V0376_
      1 "NORMAL BIRTH WEIGHT"
      2 "MODERATELY LOW BIRTH WEIGHT"
      3 "VERY LOW BIRTH WEIGHT"
      -9 "NOT ASCERTAINED"
   ;
   label define V0377_
      1 "SINGLETON"
      2 "TWIN"
      3 "HIGHER ORDER"
      -9 "NOT ASCERTAINED"
   ;
   label define V0379_
      1 "BSF-R MOTOR ADMINISTERED, NO MODIFICATIONS"
      2 "BSF-R MOTOR ADMINISTERED, WITH MODIFICATIONS"
      3 "BSF-R MOTOR ADMINISTERED, UNKNOWN MODIFICATION STATUS"
      4 "NOT SCOREABLE"
      5 "NOT ADMINISTERED"
   ;
   label define V0390_
      1 "JANUARY"
      2 "FEBRUARY"
      3 "MARCH"
      4 "APRIL"
      5 "MAY"
      6 "JUNE"
      7 "JULY"
      8 "AUGUST"
      9 "SEPTEMBER"
      10 "OCTOBER"
      11 "NOVEMBER"
      12 "DECEMBER"
   ;
   label define V0391_
      0 "COUNTY OF 1,000,000 OR MORE"
      1 "COUNTY OF   500,000 TO 1,000,000"
      2 "COUNTY OF   250,000 TO   500,000"
      3 "COUNTY OF   100,000 TO   250,000"
      4 "BALANCE OF COUNTIES (I.E. COUNTY OF LESS THAN 100,000)"
   ;
   label define V0392_
      0 "COUNTY OF 1,000,000 OR MORE"
      1 "COUNTY OF   500,000 TO 1,000,000"
      2 "COUNTY OF   250,000 TO   500,000"
      3 "COUNTY OF   100,000 TO   250,000"
      4 "BALANCE OF COUNTIES (I.E. COUNTY OF LESS THAN 100,000)"
      -6 "BIRTH TO FOREIGN RESIDENT - NO DATA"
   ;
   label define V0393_
      1 "MALE"
      2 "FEMALE"
   ;
   label define V0394_
      1 "MOTHER MARRIED"
      2 "MOTHER UNMARRIED"
      9 "UNKNOWN OR NOT STATED"
   ;
   label define V0396_
      0 "NO FORMAL EDUCATION"
      1 "1 YEAR OF ELEMENTARY SCHOOL"
      2 "2 YEARS OF ELEMENTARY SCHOOL"
      3 "3 YEARS OF ELEMENTARY SCHOOL"
      4 "4 YEARS OF ELEMENTARY SCHOOL"
      5 "5 YEARS OF ELEMENTARY SCHOOL"
      6 "6 YEARS OF ELEMENTARY SCHOOL"
      7 "7 YEARS OF ELEMENTARY SCHOOL"
      8 "8 YEARS OF ELEMENTARY SCHOOL"
      9 "1 YEAR OF HIGH SCHOOL"
      10 "2 YEARS OF HIGH SCHOOL"
      11 "3 YEARS OF HIGH SCHOOL"
      12 "4 YEARS OF HIGH SCHOOL"
      13 "1 YEAR OF COLLEGE"
      14 "2 YEARS OF COLLEGE"
      15 "3 YEARS OF COLLEGE"
      16 "4 YEARS OF COLLEGE"
      17 "5 OR MORE YEARS OF COLLEGE"
      99 "NOT STATED"
   ;
   label define V0412_
      1 "ALABAMA"
      2 "ALASKA"
      4 "ARIZONA"
      5 "ARKANSAS"
      6 "CALIFORNIA"
      8 "COLORADO"
      9 "CONNECTICUT"
      10 "DELAWARE"
      11 "DISTRICT OF COLUMBIA"
      12 "FLORIDA"
      13 "GEORGIA"
      15 "HAWAII"
      16 "IDAHO"
      17 "ILLINOIS"
      18 "INDIANA"
      19 "IOWA"
      20 "KANSAS"
      21 "KENTUCKY"
      22 "LOUISIANA"
      23 "MAINE"
      24 "MARYLAND"
      25 "MASSACHUSETTS"
      26 "MICHIGAN"
      27 "MINNESOTA"
      28 "MISSISSIPPI"
      29 "MISSOURI"
      30 "MONTANA"
      31 "NEBRASKA"
      32 "NEVADA"
      33 "NEW HAMPSHIRE"
      34 "NEW JERSEY"
      35 "NEW MEXICO"
      36 "NEW YORK"
      37 "NORTH CAROLINA"
      38 "NORTH DAKOTA"
      39 "OHIO"
      40 "OKLAHOMA"
      41 "OREGON"
      42 "PENNSYLVANIA"
      44 "RHODE ISLAND"
      45 "SOUTH CAROLINA"
      46 "SOUTH DAKOTA"
      47 "TENNESSEE"
      48 "TEXAS"
      49 "UTAH"
      50 "VERMONT"
      51 "VIRGINIA"
      53 "WASHINGTON"
      54 "WEST VIRGINIA"
      55 "WISCONSIN"
      56 "WYOMING"
      60 "AMERICAN SAMOA"
      66 "GUAM"
      69 "NORTHERN MARIANAS"
      72 "PUERTO RICO"
      78 "VIRGIN ISLANDS"
   ;
   label define V0424_
      1 "NOT AT ALL"
      2 "ONCE OR TWICE"
      3 "3 TO 6 TIMES"
      4 "EVERY DAY"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0461_
      1 "EXCELLENT"
      2 "VERY GOOD"
      3 "GOOD"
      4 "FAIR"
      5 "POOR"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0466_
      1 "OWN YOUR OWN HOME"
      2 "RENT YOUR HOUSE OR APARTMENT"
      3 "EXCHANGE SERVICES FOR HOUSING"
      4 "LIVE WITH FRIENDS OR RELATIVES AND PAY PART OF THE EXPENSES"
      5 "LIVE WITH FRIENDS OR RELATIVES AND NOT PAY FOR HOUSING"
      6 "NOT PAY FOR HOUSING AS PART OF JOB (E.G. MILITARY, CLERGY)"
      7 "LIVE IN TEMPORARY HOUSING OR A SHELTER"
      91 "HAVE ANOTHER TYPE OF HOUSING ARRANGEMENT (SPECIFY)"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0467_
      1 "A HOUSE OR TOWNHOUSE"
      2 "AN APARTMENT OR CONDOMINIUM"
      3 "A MOBILE HOME OR TRAILER"
      4 "A COMMUNITY SHELTER"
      5 "A HOTEL OR MOTEL ROOM"
      6 "ARE YOU HOMELESS"
      91 "DO YOU LIVE IN ANOTHER TYPE OF HOUSING (SPECIFY)"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0474_
      0 "ENGLISH"
      1 "ARABIC"
      2 "CHINESE"
      3 "FILIPINO LANGUAGE"
      4 "FRENCH"
      5 "GERMAN"
      6 "GREEK"
      7 "ITALIAN"
      8 "JAPANESE"
      9 "KOREAN"
      10 "POLISH"
      11 "PORTUGUESE"
      12 "SPANISH"
      13 "VIETNAMESE"
      14 "AFRICAN"
      15 "EAST EUROPEAN"
      16 "NATIVE AMERICAN"
      17 "SIGN LANGUAGE"
      18 "MIDDLE EASTERN"
      19 "WEST EUROPEAN"
      20 "INDIAN SUBCONTINENT"
      21 "SOUTHEAST ASIAN"
      22 "PACIFIC ISLAND"
      23 "CANNOT CHOOSE"
      91 "SOME OTHER LANGUAGE (SPECIFY)"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0477_
      1 "MARRIED"
      2 "SEPARATED"
      3 "DIVORCED"
      4 "WIDOWED"
      5 "HAVE YOU NEVER BEEN MARRIED"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0488_
      1 "AGREE"
      2 "DISAGREE"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0509_
      1 "RARELY OR NEVER [LESS THAN 1 DAY]"
      2 "SOME OR A LITTLE [1-2 DAYS]"
      3 "OCCASIONALLY OR MODERATE [3-4 DAYS]"
      4 "MOST OR ALL [5-7 DAYS]"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0517_
      1 "CONSTANTLY OFF TASK, DOES NOT ATTEND"
      2 "TYPICALLY OFF TASK, ATTENDS IN ONE OR TWO INSTANCES"
      3 "OFF TASK HALF THE TIME"
      4 "TYPICALLY ATTENDS, ATTENTION WANDERS IN ONE OR TWO INSTANCES"
      5 "CONSTANTLY ATTENDS"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0520_
      1 "THREE OR MORE INTENSE, HEIGHTENED, OR PROLONGED DISPLAYS OF NEGATIVE AFFECT"
      2 "ONE OR TWO INTENSE, HEIGHTENED, OR PROLONGED DISPLAYS OF NEGATIVE AFFECT"
      3 "THREE OR MORE BRIEF DISPLAYS OF NEGATIVE AFFECT"
      4 "ONE OR TWO BRIEF DISPLAYS OF NEGATIVE AFFECT"
      5 "NO NEGATIVE AFFECT DISPLAYED"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0522_
      1 "NO POSITIVE AFFECT DISPLAYED"
      2 "ONE OR TWO BRIEF DISPLAYS OF POSITIVE AFFECT"
      3 "THREE OR MORE BRIEF DISPLAYS OF POSITIVE AFFECT"
      4 "ONE OR TWO INTENSE, HEIGHTENED, OR PROLONGED DISPLAYS OF POSITIVE AFFECT"
      5 "THREE OR MORE INTENSE, HEIGHTENED, OR PROLONGED DISPLAYS OF POSITIVE AFFECT"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0523_
      1 "NO ATTEMPTS TO INTERACT SOCIALLY"
      2 "ONE OR TWO ATTEMPTS TO INTERACT SOCIALLY"
      3 "SEVERAL ATTEMPTS TO INTERACT SOCIALLY"
      4 "MANY ATTEMPTS TO INTERACT SOCIALLY"
      5 "CONSTANT ATTEMPTS TO INTERACT SOCIALLY"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0531_
      1 "NOT AT ALL"
      2 "ONCE OR TWICE"
      3 "3 TO 6 TIMES"
      4 "EVERY DAY"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0603_
      2001 "2001"
   ;
   label define V0609_
      1 "BIOLOGICAL FATHER R1 AND R2"
      2 "BIOLOGICAL FATHER R1, OTHER FATHER R2"
      3 "BIOLOGICAL FATHER R1, NO FATHER R2"
      4 "OTHER FATHER R1, BIOLOGICAL FATHER R2"
      5 "OTHER FATHER R1 AND R2, SAME PERSON"
      6 "OTHER FATHER R1 AND R2, DIFFERENT PERSON"
      7 "OTHER FATHER R1, NO FATHER R2"
      8 "NO FATHER R1, BIOLOGICAL FATHER R2"
      9 "NO FATHER R1, OTHER FATHER R2"
      10 "NO FATHER R1 AND R2"
   ;
   label define V0611_
      95 "CHILD NOT YET ABLE TO CRAWL"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0617_
      95 "CHILD NOT YET ABLE TO SIT ALONE WITHOUT SUPPORT"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0619_
      95 "CHILD NOT YET ABLE TO WALK"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0645_
      -9 "NOT ASCERTAINED"
   ;
   label define V0659_
      0 "DID NOT PASS EITHER BLOCK ITEM"
      1 "PASSED ONE OF THE BLOCK ITEMS"
      2 "PASSED BOTH OF THE BLOCK ITEMS"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0660_
      0 "NO NONPARENTAL CARE"
      1 "RELATIVE CARE IN CHILD'S HOME"
      2 "RELATIVE CARE IN ANOTHER HOME"
      3 "RELATIVE CARE, LOCATION VARIES"
      4 "NONRELATIVE CARE IN CHILD'S HOME"
      5 "NONRELATIVE CARE IN ANOTHER HOME"
      6 "NONRELATIVE CARE, LOCATION VARIES"
      7 "CENTER-BASED PROGRAM"
      8 "HEAD START PROGRAM"
      9 "MULTIPLE CARE ARRANGEMENTS WITH SAME HOURS IN EACH"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0665_
      1 "YES"
      2 "NO"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0667_
      1 "8TH GRADE OR BELOW"
      2 "9TH TO 12TH GRADES"
      3 "HIGH SCHOOL DIPLOMA/ EQUIVALENT"
      4 "VOC/TECH PROGRAM"
      5 "SOME COLLEGE"
      6 "BACHELOR'S DEGREE"
      7 "GRADUATE PROFESSIONAL SCHOOL/ NO DEGREE"
      8 "MASTER'S DEGREE (MA/MS)"
      9 "DOCTORATE OR PROFESSIONAL DEGREE"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0668_
      1 "BIRTH MOTHER"
      2 "ADOPTIVE MOTHER"
      3 "STEP MOTHER"
      4 "FOSTER MOTHER"
      5 "REL/NONREL RESP-MOTHER FIG"
      6 "FATHER'S PARTNER-MOTHER FIG"
      7 "REL/NONREL RESPS PARTNER-MOTHER FIG"
      8 "MOTHER-UNKNOWN TYPE"
      9 "NO RESIDENT MOTHER"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0669_
      1 "WHITE, NON-HISPANIC"
      2 "BLACK OR AFRICAN AMERICAN, NON-HISPANIC"
      3 "HISPANIC, RACE SPECIFIED"
      4 "HISPANIC, NO RACE SPECIFIED"
      5 "ASIAN, NON-HISPANIC"
      6 "NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER, NON-HISPANIC"
      7 "AMERICAN INDIAN OR ALASKA NATIVE, NON-HISPANIC"
      8 "MORE THAN 1 RACE, NON-HISPANIC"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0670_
      1 "35 HOURS OR MORE PER WEEK"
      2 "LESS THAN 35 HOURS PER WEEK"
      3 "LOOKING FOR WORK"
      4 "NOT IN THE LABOR FORCE"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0671_
      1 "MANAGEMENT OCCUPATION"
      2 "BUSINESS AND FINANCIAL OPERATIONS OCCUPATIONS"
      3 "COMPUTER AND MATHEMATICAL OCCUPATIONS"
      4 "ARCHITECTURE AND ENGINEERING"
      5 "LIFE,PHYSICAL AND SOCIAL SCIENCE"
      6 "COMMUNITY AND SOCIAL SERVICE"
      7 "LEGAL"
      8 "EDUCATION,TRAINING AND LIBRARY OCCUPATIONS"
      9 "ARTS,DESIGN,ENTERTAINMENT,SPORTS AND MEDIA"
      10 "HEALTHCARE PRACTITIONER AND TECHNICAL"
      11 "HEALTHCARE SUPPORT"
      12 "PROTECTIVE SERVICE"
      13 "FOOD PREPARATION AND SERVING RELATED"
      14 "BUILDING AND GROUNDS CLEANING AND MAINTENANCE"
      15 "PERSONAL CARE AND SERVICES"
      16 "SALES AND RELATED OCCUPATIONS"
      17 "OFFICE AND ADMINISTRATIVE SUPPORT"
      18 "FARMING,FISHING AND FORESTRY"
      19 "CONSTRUCTION AND EXTRACTION OCCUPATIONS"
      20 "INSTALLATION,MAINTENANCE AND REPAIR"
      21 "PRODUCTION"
      22 "TRANSPORTATION AND MATERIAL MOVING OCCUPATIONS"
      23 "MILITARY SPECIFIC OCCUPATIONS"
      90 "NOT IN THE LABOR FORCE (RETIRED, DISABLED, UNCLASSIFIED)"
      99 "UNEMPLOYED, ACTIVELY LOOKING FOR WORK"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0672_
      1 "BIRTH FATHER"
      2 "ADOPTIVE FATHER"
      3 "STEP FATHER"
      4 "FOSTER FATHER"
      5 "REL/NONREL RESP-FATHER FIG"
      6 "MOTHER'S PARTNER-FATHER FIG"
      7 "REL/NONREL RESPS PARTNER-FATHER FIG"
      8 "FATHER-UNKNOWN TYPE"
      9 "NO RESIDENT FATHER"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0673_
      1 "SAME PERSON, R1/R2/R3"
      2 "SAME PERSON, R1/R3 (R2 NOT THE SAME)"
      3 "SAME PERSON, R1/R2 (R3 NOT THE SAME)"
      4 "SAME PERSON, R2/R3 (R1 NOT THE SAME)"
      5 "OTHER PATTERN"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0674_
      1 "BIOLOGICAL MOTHER AND BIOLOGICAL FATHER"
      2 "BIOLOGICAL MOTHER AND OTHER FATHER"
      3 "BIOLOGICAL FATHER AND OTHER MOTHER"
      4 "BIOLOGICAL MOTHER ONLY"
      5 "BIOLOGICAL FATHER ONLY"
      6 "TWO ADOPTIVE PARENTS"
      7 "SINGLE ADOPTIVE PARENT OR ADOPTIVE AND STEP PARENT"
      8 "RELATED GUARDIAN(S)"
      9 "UNRELATED GUARDIAN(S)"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0675_
      1 "MARRIED"
      2 "SEPARATED"
      3 "DIVORCED"
      4 "WIDOWED"
      5 "NEVER MARRIED"
      6 "NON BIO OR ADOPTIVE PARENTS"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0676_
      1 "NON-ENGLISH LANGUAGE"
      2 "ENGLISH LANGUAGE"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0681_
      1 "$5,000 OR LESS"
      2 "$5,001 TO $10,000"
      3 "$10,001 TO $15,000"
      4 "$15,001 TO $20,000"
      5 "$20,001 TO $25,000"
      6 "$25,001 TO $30,000"
      7 "$30,001 TO $35,000"
      8 "$35,001 TO $40,000"
      9 "$40,001 TO $50,000"
      10 "$50,001 TO $75,000"
      11 "$75,001 TO $100,000"
      12 "$100,001 TO $200,000"
      13 "$200,001 OR MORE"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0682_
      1 "FIRST QUINTILE (LOWEST)"
      2 "SECOND QUINTILE"
      3 "THIRD QUINTILE"
      4 "FOURTH QUINTILE"
      5 "FIFTH QUINTILE (HIGHEST)"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0683_
      1 "NORTHEAST"
      2 "MIDWEST"
      3 "SOUTH"
      4 "WEST"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0684_
      1 "URBAN, INSIDE UA"
      2 "URBAN, INSIDE UC"
      3 "RURAL"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0685_
      11 "CITY-LARGE"
      12 "CITY-MIDSIZE"
      13 "CITY-SMALL"
      21 "SUBURBAN-LARGE"
      22 "SUBURBAN-MIDSIZE"
      23 "SUBURBAN-SMALL"
      31 "TOWN-FRINGE"
      32 "TOWN-DISTANT"
      33 "TOWN-REMOTE"
      41 "RURAL-FRINGE"
      42 "RURAL-DISTANT"
      43 "RURAL-REMOTE"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0690_
      1 "YES, COMPLETE"
      2 "NO, NO REGULAR CHILD CARE REPORTED"
      3 "NO, PARENT DID NOT SIGN CONSENT FORM"
      4 "NO, NOT ELIGIBLE"
      5 "NO, NOT FIELDED FOR ECEP"
      7 "NO, ECEP REFUSAL"
      8 "NO, ECEP OTHER NONRESPONSE"
      9 "NO, UNDERAGE (IN AND OUT OF WA)"
      10 "NO, TWINS ARE NOT IN SAME CARE FACILITY"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0691_
      1 "YES, COMPLETE"
      2 "NO, SAQ NOT ADMINISTERED BECAUSE NO REGULAR CARE"
      3 "NO, SAQ NOT ADMINISTERED, CCO NOT COMPLETE"
      4 "NO, CCO COMPLETED, NOT ELIGIBLE FOR CDSAQ-HOME BASED OBSRVTN"
      5 "NO, COMPLETED CENTER-BASED OBSERVATION, SAQ REFUSAL"
      6 "NO, COMPLETED CENTER-BASED OBSERVATION, OTHER NONRESPONSE"
      7 "NO, UNDERAGE (IN AND OUT OF WA)"
      81 "NO, CASE NOT SELECTED - CASE FROM ALASKA / HAWAII"
      82 "NO, CASE NOT SELECTED - CASE FROM SPECIAL AMERICAN INDIAN SAMPLE"
      83 "NO, CASE NOT SELECTED - BASED ON SAMPLE SELECTION PROBLEM"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0692_
      1 "YES, COMPLETE"
      2 "NO, NO REGULAR CHILD CARE REPORTED"
      3 "NO, NOT SELECTED, NO ARRANGEMENT = OR > 10 HOURS PER WEEK"
      4 "NO, SELECTED FOR CCO BUT PARENT DID NOT SIGN CONSENT FORM"
      5 "NO, SELECTED FOR CCO BUT ECEP PARTIAL/PROBLEM/COMP LATE"
      6 "NO, SELECTED FOR CCO, ECEP COMPLETE, REFUSED CCO IN THE ECEP"
      7 "NO, NOT FIELDED FOR CCO, LANG OTHER THAN ENGLISH OR SPANISH"
      8 "NO, FIELDED FOR CCO BUT PROVIDER NOT ELIGIBLE"
      10 "NO, CCO REFUSAL"
      11 "NO, CCO OTH NRSP(TOO FAR/LNG PRB/NONLOC/STPPD WRK/NOT RCPTD)"
      12 "NO, TWINS IN SAME CARE FACILITY, BUT ECEP RESPONDENT NOT FOR THIS CHILD"
      13 "NO, NOT FIELDED FOR CCO, MINOR PROVIDER"
      81 "NO, CASE WAS NOT SELECTED BECAUSE CASE WAS FRM ALASKA/HAWAII"
      82 "NO, CASE NOT SELECTED-CASE FROM SPECIAL AMER. INDIAN SAMPLE"
      83 "NO, REG CH CARE NOT SELECTED BASED ON SMPL SLCTN PROB"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0699_
      1 "YES"
      2 "NO"
      -1 "NOT ELIGIBLE FOR RESIDENT FATHER SAQ"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0701_
      0 "NOT IMPUTED"
      1 "IMPUTED"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0712_
      1 "ALL OF THE LETTERS OF THE ALPHABET"
      2 "MOST OF THEM"
      3 "SOME OF THEM"
      4 "NONE OF THEM"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0715_
      1 "NOT AT ALL"
      2 "UP TO FIVE"
      3 "UP TO TEN"
      4 "UP TO TWENTY"
      5 "UP TO FIFTY"
      6 "UP TO 100 OR MORE"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0716_
      1 "ALWAYS"
      2 "FREQUENTLY"
      3 "SOMETIMES"
      4 "RARELY"
      5 "NOT AT ALL"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0720_
      0 "ENGLISH"
      1 "ARABIC"
      2 "CHINESE"
      3 "FILIPINO LANGUAGE"
      4 "FRENCH"
      5 "GERMAN"
      6 "GREEK"
      7 "ITALIAN"
      8 "JAPANESE"
      9 "KOREAN"
      10 "POLISH"
      11 "PORTUGUESE"
      12 "SPANISH"
      13 "VIETNAMESE"
      14 "AFRICAN"
      15 "EAST EUROPEAN"
      16 "NATIVE AMERICAN"
      17 "SIGN LANGUAGE"
      18 "MIDDLE EASTERN"
      19 "WEST EUROPEAN"
      20 "INDIAN SUBCONTINENT"
      21 "SOUTHEAST ASIAN"
      22 "PACIFIC ISLAND"
      23 "CANNOT CHOOSE"
      91 "SOME OTHER LANGUAGE (SPECIFY)"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0722_
      1 "NOT AT ALL"
      2 "ONCE OR TWICE"
      3 "3 TO 6 TIMES"
      4 "EVERY DAY"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0731_
      1 "TO RECEIVE LESS THAN A HIGH SCHOOL DIPLOMA"
      2 "TO GRADUATE FROM HIGH SCHOOL"
      3 "TO ATTEND TWO OR MORE YEARS OF COLLEGE"
      4 "TO FINISH A 4- OR 5-YEAR COLLEGE DEGREE"
      5 "TO EARN A MASTERS DEGREE OR EQUIVALENT"
      6 "TO FINISH A PH.D., M.D., OR OTHER ADVANCED DEGREE"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0748_
      1 "EXCELLENT"
      2 "VERY GOOD"
      3 "GOOD"
      4 "FAIR"
      5 "POOR"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0760_
      1 "MARRIED"
      2 "SEPARATED"
      3 "DIVORCED"
      4 "WIDOWED"
      5 "NEVER BEEN MARRIED"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0783_
      1 "A HOUSE OR TOWNHOUSE"
      2 "AN APARTMENT OR CONDOMINIUM"
      3 "A MOBILE HOME OR TRAILER"
      4 "A COMMUNITY SHELTER"
      5 "A HOTEL OR MOTEL ROOM"
      6 "ARE YOU HOMELESS"
      91 "DO YOU LIVE IN ANOTHER TYPE OF HOUSING (SPECIFY)"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0784_
      1 "OWN YOUR OWN HOME"
      2 "RENT YOUR HOUSE OR APARTMENT"
      3 "EXCHANGE SERVICES FOR HOUSING"
      4 "LIVE WITH FRIENDS OR RELATIVES AND PAY PART OF THE EXPENSES"
      5 "LIVE WITH FRIENDS OR RELATIVES  AND NOT PAY FOR HOUSING"
      6 "NOT PAY FOR HOUSING AS PART OF A JOB"
      7 "LIVE IN TEMPORARY HOUSING OR A SHELTER"
      91 "HAVE ANOTHER TYPE OF HOUSING ARRANGEMENT (SPECIFY)"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0808_
      1 "NOT AT ALL"
      2 "ONCE OR TWICE A WEEK"
      3 "3 TO 6 TIMES A WEEK"
      4 "EVERY DAY"
      -1 "NOT APPLICABLE"
      -9 "NOT ASCERTAINED"
   ;
   label define V0931_
      1 "YES, COMPLETE"
      2 "NO, CHILD IN KINDERGARTEN OR HIGHER"
      3 "NO REGULAR CHILD CARE REPORTED"
      5 "NO, PARENT DID NOT SIGN CONSENT FORM"
      6 "NO, NOT ELIGIBLE"
      7 "NO, NOT FIELDED FOR ECEP"
      8 "NO, ECEP REFUSAL"
      9 "NO, ECEP OTHER NONRESPONSE"
      10 "NO, UNDERAGE"
      11 "NO, TWINS ARE NOT IN SAME CARE FACILITY"
      12 "NO, GRADE AND CHILD CARE STATUS UNKNOWN"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0947_
      0 "NO TWO BAGS TAPE"
      1 "TWO BAGS TAPE CODED"
      2 "NO, TWO BAGS TAPE NOT CODEABLE"
   ;
   label define V0948_
      1 "YES, COMPLETE"
      2 "NO, CHILD NOT IN KINDERGARTEN"
      3 "NO REGULAR CHILD CARE REPORTED"
      4 "NO, TIME CRITERIA FOR CARE/SCHL NOT MET"
      5 "NO, PARENT DID NOT SIGN CONSENT FORM"
      6 "NO, NOT ELIGIBLE"
      7 "NO, NOT FIELDED FOR WECEP"
      8 "NO, WECEP REFUSAL"
      9 "NO, WECEP OTHER NONRESPONSE"
      10 "NO, UNDERAGE"
      11 "NO, TWINS ARE NOT IN SAME CARE FACILITY"
      12 "NO, GRADE OR CHILD CARE STATUS UNKNOWN"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0949_
      0 "NOT SUBSAMPLED FOR RAPT"
      1 "SUBSAMPLED FOR RAPT"
   ;
   label define V0950_
      1 "TEACHER COMPLETE"
      2 "ENROLLMENT IN K OR HIGHER NOT REPORTED"
      3 "CHILD IN K OR HIGHER, BUT IS HOMESCHOOLED"
      4 "DO NOT HAVE PARENTAL CONSENT FOR TEACHER SURVEY"
      5 "DISTRICT OR SCHOOL REFUSAL"
      6 "FIELDED FOR TEACHER SURVEY, BUT FACILITY INELIGIBLE"
      7 "FIELDED FOR TEACHER SURVEY, BUT UNABLE TO LOCATE TEACHER"
      8 "FIELDED FOR TEACHER SURVEY, BUT TEACHER NO LONGER AT THE SCHOOL"
      9 "FIELDED FOR TEACHER SURVEY, BUT CHILD NOT IN K OR HIGHER"
      10 "FIELDED FOR TEACHER SURVEY, BUT CHILD NO LONGER TAUGHT BY TEACHER"
      11 "TEACHER REFUSAL"
      12 "OTHER TEACHER NONRESPONSE"
      13 "SCHOOL ENROLLMENT STATUS UNKNOWN"
   ;
   label define V0951_
      0 "IN PRESCHOOL / NOT IN SCHOOL"
      1 "IN KINDERGARTEN"
      2 "IN 1ST OR 2ND GRADE"
      3 "UNGRADED OR OTHER"
      4 "HOME SCHOOLED"
      -9 "NOT ASCERTAINED"
   ;
   label define V0952_
      1 "INELIGIBLE FOR SUBSAMPLE"
      2 "ELIGIBLE, PART OF SUBSAMPLE"
      3 "ELIGIBLE, NOT  SUBSAMPLED"
      -9 "NOT ASCERTAINED"
   ;
   label define V0955_
      1 "PSS 03/04"
      2 "PSS 05/06"
      3 "PSS ID ONLY, NO DATA AVAILABLE IN 03/04 OR 05/06 PSS"
      4 "CCD 06/07"
      99 "SCHOOL DATA DID NOT MATCH CCD OR PSS"
      -1 "NOT APPLICABLE"
      -2 "N/A, TEACHER SURVEY NOT FIELDED OR FACILITY INELIG"
      -9 "NOT ASCERTAINED"
   ;
   label define V0958_
      1 "JANUARY"
      2 "FEBRUARY"
      3 "MARCH"
      4 "APRIL"
      5 "MAY"
      6 "JUNE"
      7 "JULY"
      8 "AUGUST"
      9 "SEPTEMBER"
      10 "OCTOBER"
      11 "NOVEMBER"
      12 "DECEMBER"
      -9 "NOT ASCERTAINED"
   ;
   label define V0959_
      1 "JANUARY"
      2 "FEBRUARY"
      3 "MARCH"
      4 "APRIL"
      5 "MAY"
      6 "JUNE"
      7 "JULY"
      8 "AUGUST"
      9 "SEPTEMBER"
      10 "OCTOBER"
      11 "NOVEMBER"
      12 "DECEMBER"
      -9 "NOT ASCERTAINED"
   ;
   label define V0960_
      2001 "2001"
      2002 "2002"
      -9 "NOT ASCERTAINED"
   ;
   label define V0961_
      2003 "2003"
      2004 "2004"
   ;
   label define V0962_
      2005 "2005"
      2006 "2006"
   ;
   label define V0963_
      2006 "2006"
      2007 "2007"
   ;
   label define V0974_
      2007 "2007"
      2008 "2008"
      -9 "NOT ASCERTAINED"
   ;
   label define V0985_
      1 "YES, COMPLETE"
      2 "NO, CHILD NOT IN KINDERGARTEN"
      3 "NO REGULAR CHILD CARE REPORTED"
      4 "NO, HRS OF CARE < REQUIRED"
      5 "NO, PARENT DID NOT SIGN CONSENT FORM"
      6 "NO, NOT ELIGIBLE"
      7 "NO, NOT FIELDED FOR WECEP"
      8 "NO, WECEP REFUSAL"
      9 "NO, WECEP OTHER NONRESPONSE"
      10 "NO, UNDERAGE"
      11 "NO, TWINS ARE NOT IN SAME CARE FACILITY"
      12 "NO, GRADE OR CHILD CARE STATUS UNKNOWN"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0986_
      1 "NOT ELIGIBLE FOR K07 -- K06 FIRST GRADER"
      2 "K07 CORE SAMPLE (CHILD NOT IN K OR HIGHER IN K06)"
      3 "K07 CORE SAMPLE (SCHOOL INDICATED NOT IN K OR HIGHER IN K06)"
      4 "SCREENER RESPONDENT -- CHILD LIKELY A REPEATER"
      5 "SCREENER RESPONDENT -- NOT LIKELY A REPEATER"
      6 "SCREENER RESPONDENT -- DETERMINED TO BE INELIGIBLE"
      7 "SCREENER NONRESPONSE -- UNLOCATABLE"
      8 "SCREENER NONRESPONSE -- OTHER"
      9 "NOT ELIGIBLE FOR K07, INCLUDED BECAUSE TWIN WAS ELIGIBLE"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0987_
      1 "NOT ENROLLED IN SCHOOL K06 OR K07                          "
      2 "K06 FIRST TIME KINDERGARTENER                              "
      3 "K07 FIRST TIME KINDERGARTENER                              "
      4 "STRAIGHT TO FIRST GRADE IN K06                             "
      5 "STRAIGHT TO FIRST GRADE IN K07                             "
      6 "FIRST ENROLLED IN SCHOOL IN K06 (GRADE UNKNOWN OR UNGRADED)"
      7 "FIRST ENROLLED IN SCHOOL IN K07 (GRADE UNKNOWN OR UNGRADED)"
      8 "HOMESCHOOLED (K06 FIRST TIME BEING HOMESCHOOLED)"
      9 "HOMESCHOOLED (K07 FIRST TIME BEING HOMESCHOOLED)           "
      99 "UNKNOWN"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0988_
      1 "K06"
      2 "K07"
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
   ;
   label define V0989_
      1 "YES, CHLD REPEATING KINDERGARTEN         "
      2 "NO, CHLD NOT REPEATING KINDERGARTEN      "
      3 "CHLD IN 2-YR, TRANSITIONAL, OR UNGRD PRG "
      -1 "NOT APPLICABLE"
      -7 "REFUSED"
      -8 "DON'T KNOW"
      -9 "NOT ASCERTAINED"
;
   label values F2READBO V0021_;
   label values F2TELLST V0021_;
   label values P2READBO V0021_;
   label values P2TELLST V0021_;
   label values F2MDEPFA V0027_;
   label values F2MDEPMO V0027_;
   label values P2ALLRGY V0027_;
   label values P2ASMAFA V0027_;
   label values P2ASMAMO V0027_;
   label values P2ASTHMA V0027_;
   label values P2FDALRY V0027_;
   label values P2FDSTMP V0027_;
   label values P2FMASMA V0027_;
   label values P2GVHSNG V0027_;
   label values P2MDEPFA V0027_;
   label values P2MDEPMO V0027_;
   label values P2MEDICD V0027_;
   label values P2RESPIL V0027_;
   label values P2VSTLIB V0027_;
   label values P2WELFR V0027_;
   label values P2WICBFT V0027_;
   label values P2CMBWRD V0031_;
   label values P2OGAME V0066_;
   label values P2CHEALT V0072_;
   label values P2HSSIT V0075_;
   label values P2HSTYPE V0076_;
   label values P2PRMLNG V0083_;
   label values P2CRMRST V0089_;
   label values R2NEGAFF V0119_;
   label values R2POSAFF V0120_;
   label values R2SOCIAL V0121_;
   label values R2ATNTSK V0123_;
   label values X2STCDSQ V0258_;
   label values X2STTAS V0259_;
   label values X2STTB V0260_;
   label values X2STTRFQ V0262_;
   label values X2TASCLS V0268_;
   label values X2STTNRQ V0270_;
   label values X2STCCP V0271_;
   label values Y2HFEMP V0275_;
   label values Y2HMEMP V0275_;
   label values X2INCOME V0276_;
   label values X2NRFED V0279_;
   label values Y2HPARNT V0282_;
   label values Y2FTHTYP V0283_;
   label values Y2MOMTYP V0284_;
   label values X2STBMTL V0286_;
   label values X2STBMTR V0287_;
   label values Y1SESQ5 V0289_;
   label values Y2SESQ5 V0289_;
   label values Y2FTHOCC V0292_;
   label values Y2MOMOCC V0292_;
   label values Y2MARSTA V0293_;
   label values Y2PRIMNW V0294_;
   label values X1LANGST V0295_;
   label values X2PRMLNG V0295_;
   label values X1HHREGN V0296_;
   label values X2HHREGN V0296_;
   label values X1IFHINC V0297_;
   label values X2IFHINC V0297_;
   label values Y2HFRACE V0299_;
   label values Y2HMRACE V0299_;
   label values P1ASTHMA V0302_;
   label values P1FDSTMP V0302_;
   label values P1GVHSNG V0302_;
   label values P1MEDICD V0302_;
   label values P1RESPIL V0302_;
   label values P1WELFR V0302_;
   label values P1WICBFT V0302_;
   label values P1WICPRG V0302_;
   label values X2HHURBN V0306_;
   label values X2STCCO V0309_;
   label values X1APNCU V0312_;
   label values X1BWT250 V0313_;
   label values P2FRSTWD V0317_;
   label values BCBRTHWT V0327_;
   label values P1HMVALU V0327_;
   label values P2HMVALU V0327_;
   label values P2NMKDBK V0327_;
   label values P2NMPLTY V0327_;
   label values P2NMREC V0327_;
   label values P2NMSFTY V0327_;
   label values P3HMVALU V0327_;
   label values P3TIMAST V0327_;
   label values P4HMVALU V0327_;
   label values P4RMONTH V0327_;
   label values P4RYEARS V0327_;
   label values P5RMONTH V0327_;
   label values P5RYEARS V0327_;
   label values X1ASAGE V0327_;
   label values X1CHLENG V0327_;
   label values X1CHPREM V0327_;
   label values X1CHWGHT V0327_;
   label values X1HFAG_B V0327_;
   label values X1HMAG_B V0327_;
   label values X1RMTLS V0327_;
   label values X1RMTRS V0327_;
   label values X2ASAGE V0327_;
   label values X2CHHGHT V0327_;
   label values X2CHWGHT V0327_;
   label values X2HFAG_B V0327_;
   label values X2HMAG_B V0327_;
   label values X2ITRLT V0327_;
   label values X2MTLSCL V0327_;
   label values X2MTRSCL V0327_;
   label values X3ASAGE V0327_;
   label values X3CHHGHT V0327_;
   label values X3CHWGHT V0327_;
   label values X3ECRLT V0327_;
   label values X3FMFORM V0327_;
   label values X3HFAG_B V0327_;
   label values X3HMAG_B V0327_;
   label values X3MSCR2 V0327_;
   label values X3MSER2 V0327_;
   label values X3RSCR2 V0327_;
   label values X3RSER2 V0327_;
   label values X418OVER V0327_;
   label values X4ASAGE V0327_;
   label values X4ASINT V0327_;
   label values X4CHHGHT V0327_;
   label values X4CHWGHT V0327_;
   label values X4EXPLNG V0327_;
   label values X4FMFORM V0327_;
   label values X4FTHSCR V0327_;
   label values X4HFAG_B V0327_;
   label values X4HMAG_B V0327_;
   label values X4HTOTAL V0327_;
   label values X4LESS18 V0327_;
   label values X4MOMSCR V0327_;
   label values X4MSCR2 V0327_;
   label values X4MSER2 V0327_;
   label values X4NUMSIB V0327_;
   label values X4RSCR2 V0327_;
   label values X4RSER2 V0327_;
   label values X518OVER V0327_;
   label values X5ASAGE V0327_;
   label values X5ASINT V0327_;
   label values X5CHHGHT V0327_;
   label values X5CHWGHT V0327_;
   label values X5EXPLNG V0327_;
   label values X5FMFORM V0327_;
   label values X5FTHSCR V0327_;
   label values X5HFAG_B V0327_;
   label values X5HMAG_B V0327_;
   label values X5HTOTAL V0327_;
   label values X5LESS18 V0327_;
   label values X5MOMSCR V0327_;
   label values X5MSCR2 V0327_;
   label values X5MSER2 V0327_;
   label values X5NUMSIB V0327_;
   label values X5RSCR2 V0327_;
   label values X5RSER2 V0327_;
   label values Y1FTHSCR V0327_;
   label values Y1MOMSCR V0327_;
   label values Y2FTHSCR V0327_;
   label values Y2HTOTAL V0327_;
   label values Y2LESS18 V0327_;
   label values Y2MOMSCR V0327_;
   label values Y2NUMSIB V0327_;
   label values Y318OVER V0327_;
   label values Y3FTHSCR V0327_;
   label values Y3HTOTAL V0327_;
   label values Y3LESS18 V0327_;
   label values Y3MOMSCR V0327_;
   label values Y3NUMSIB V0327_;
   label values BCSTRSFP V0342_;
   label values Y1HPARNT V0345_;
   label values X1MARSTA V0346_;
   label values X1INCOME V0347_;
   label values Y1FTHTYP V0348_;
   label values Y1HFRACE V0349_;
   label values X1NRFED V0353_;
   label values Y1HFEMP V0354_;
   label values Y1FTHOCC V0355_;
   label values Y1MOMTYP V0357_;
   label values Y1HMRACE V0358_;
   label values Y1HMEMP V0360_;
   label values Y1MOMOCC V0361_;
   label values Y1PRIMNW V0364_;
   label values Y1CHRACE V0365_;
   label values X1NRFEMP V0367_;
   label values X1HHURBN V0368_;
   label values X1STBMTL V0369_;
   label values X1STTNCT V0370_;
   label values X1STTRFQ V0372_;
   label values X1STTNRQ V0373_;
   label values X1BTHWGT V0376_;
   label values X1MBRTST V0377_;
   label values X1STBMTR V0379_;
   label values BCDOBMM V0390_;
   label values BCCNOCSZ V0391_;
   label values BCCNRSSZ V0392_;
   label values X4CHSEX V0393_;
   label values BCMOMMAR V0394_;
   label values BCMOMED V0396_;
   label values BCSTOCFP V0412_;
   label values P1READBO V0424_;
   label values P1SINGSO V0424_;
   label values P1TELLST V0424_;
   label values P1CHEALT V0461_;
   label values P1HSSIT V0466_;
   label values P1HSTYPE V0467_;
   label values P1PRMLNG V0474_;
   label values P1MARSTS V0477_;
   label values P1KNWSNM V0488_;
   label values P1WRD1ST V0488_;
   label values P1DEPRES V0509_;
   label values R1ATNTSK V0517_;
   label values R1NEGAFF V0520_;
   label values R1POSAFF V0522_;
   label values R1SOCIAL V0523_;
   label values F1READBO V0531_;
   label values F1SINGSO V0531_;
   label values F1TELLST V0531_;
   label values BCDOBYY V0603_;
   label values Y2SAMERF V0609_;
   label values P1AGCRWL V0611_;
   label values P1AGSIT V0617_;
   label values P1AGWALK V0619_;
   label values X3MTHR2 V0645_;
   label values X3RTHR2 V0645_;
   label values X4MTHR2 V0645_;
   label values X4RTHR2 V0645_;
   label values X5MTHR2 V0645_;
   label values X5RTHR2 V0645_;
   label values X3FMBLCK V0659_;
   label values X4PRIMNW V0660_;
   label values X5PRIMNW V0660_;
   label values Y3PRIMNW V0660_;
   label values P3ADHD V0665_;
   label values P3ASTHMA V0665_;
   label values P3ATEVNT V0665_;
   label values P3ATMEET V0665_;
   label values P3AUTISM V0665_;
   label values P3CHAPFD V0665_;
   label values P3FDALRY V0665_;
   label values P3GOCONF V0665_;
   label values P3GVHSNG V0665_;
   label values P3RDALON V0665_;
   label values P3RESPIL V0665_;
   label values P3SMMRST V0665_;
   label values P3VOLUN V0665_;
   label values P3WICBFT V0665_;
   label values P4ADHD V0665_;
   label values P4ALLERG V0665_;
   label values P4ASTHMA V0665_;
   label values P4AUTISM V0665_;
   label values P4FDALRY V0665_;
   label values P4GVHSNG V0665_;
   label values P4KNWNAM V0665_;
   label values P4PRGSD V0665_;
   label values P4RDALON V0665_;
   label values P4RESPIL V0665_;
   label values P4SMMRST V0665_;
   label values P4WICCH2 V0665_;
   label values P5ADHD V0665_;
   label values P5ALLERG V0665_;
   label values P5AUTISM V0665_;
   label values P5FDALRY V0665_;
   label values P5GETADV V0665_;
   label values P5PRGSD V0665_;
   label values P5RDALON V0665_;
   label values P5RDBKS V0665_;
   label values P5RDSNL V0665_;
   label values P5SMMRST V0665_;
   label values P5TLKKND V0665_;
   label values P5TLKPAR V0665_;
   label values P5VOLSCH V0665_;
   label values P5VSTSCH V0665_;
   label values P5WICOCH V0665_;
   label values X4FTHED V0667_;
   label values X4MOMED V0667_;
   label values X4PARED V0667_;
   label values X5FTHED V0667_;
   label values X5MOMED V0667_;
   label values X5PARED V0667_;
   label values Y1FTHED V0667_;
   label values Y1MOMED V0667_;
   label values Y1PARED V0667_;
   label values Y2FTHED V0667_;
   label values Y2MOMED V0667_;
   label values Y2PARED V0667_;
   label values Y3FTHED V0667_;
   label values Y3MOMED V0667_;
   label values Y3PARED V0667_;
   label values X4MOMTYP V0668_;
   label values X5MOMTYP V0668_;
   label values Y3MOMTYP V0668_;
   label values X4HFRACE V0669_;
   label values X4HMRACE V0669_;
   label values X5HFRACE V0669_;
   label values X5HMRACE V0669_;
   label values Y3HFRACE V0669_;
   label values Y3HMRACE V0669_;
   label values X4HFEMP V0670_;
   label values X4HMEMP V0670_;
   label values X5HFEMP V0670_;
   label values X5HMEMP V0670_;
   label values Y3HFEMP V0670_;
   label values Y3HMEMP V0670_;
   label values X4FTHOCC V0671_;
   label values X4MOMOCC V0671_;
   label values X5FTHOCC V0671_;
   label values X5MOMOCC V0671_;
   label values Y3FTHOCC V0671_;
   label values Y3MOMOCC V0671_;
   label values X4FTHTYP V0672_;
   label values X5FTHTYP V0672_;
   label values Y3FTHTYP V0672_;
   label values Y3SAMERF V0673_;
   label values X4HPARNT V0674_;
   label values X5HPARNT V0674_;
   label values Y3HPARNT V0674_;
   label values X4MARSTA V0675_;
   label values X5MARSTA V0675_;
   label values Y3MARSTA V0675_;
   label values X3PRMLNG V0676_;
   label values X4PRMLNG V0676_;
   label values X5PRMLNG V0676_;
   label values X3INCOME V0681_;
   label values X4INCOME V0681_;
   label values X5INCOME V0681_;
   label values X4SESQ5 V0682_;
   label values Y3SESQ5 V0682_;
   label values X3HHREGN V0683_;
   label values X4HHREGN V0683_;
   label values X5HHREGN V0683_;
   label values X3HHURBN V0684_;
   label values X4HHURBN V0684_;
   label values X5HHURBN V0684_;
   label values X3CCLOCL V0685_;
   label values X3HHLOCL V0685_;
   label values X4CCLOCL V0685_;
   label values X4HHLOCL V0685_;
   label values X4WCLOCL V0685_;
   label values X5HHLOCL V0685_;
   label values X5WCLOCL V0685_;
   label values X3STCCP V0690_;
   label values X3STCDSQ V0691_;
   label values X3STCCO V0692_;
   label values X3STTRFQ V0699_;
   label values X3IFHINC V0701_;
   label values X4IFHINC V0701_;
   label values X5IFHINC V0701_;
   label values P3KNOABC V0712_;
   label values P4KNOABC V0712_;
   label values P3CHCNT V0715_;
   label values P4CHCNT V0715_;
   label values P3SPKCLR V0716_;
   label values P4PRMLNG V0720_;
   label values P3READBO V0722_;
   label values P3TELLST V0722_;
   label values P4READBO V0722_;
   label values P4TELLST V0722_;
   label values P5READBO V0722_;
   label values P5TELLST V0722_;
   label values P4SCLEXP V0731_;
   label values P3CHEALT V0748_;
   label values P4CHEALT V0748_;
   label values P5CHEALT V0748_;
   label values P3MARSTS V0760_;
   label values P4MARSTS V0760_;
   label values P5MARSTS V0760_;
   label values P3HSTYPE V0783_;
   label values P4HSTYPE V0783_;
   label values P3HSSIT V0784_;
   label values P4HSSIT V0784_;
   label values F3READBO V0808_;
   label values F3TELLST V0808_;
   label values X4STCCP V0931_;
   label values X3STTB V0947_;
   label values X4STWCP V0948_;
   label values X3STRAPT V0949_;
   label values X4STTSQ V0950_;
   label values X5STTSQ V0950_;
   label values X4GRDLVL V0951_;
   label values X5GRDLVL V0951_;
   label values X4ELIGBL V0952_;
   label values X4CCDPSS V0955_;
   label values X5CCDPSS V0955_;
   label values X1ASMTMM V0958_;
   label values X2ASMTMM V0959_;
   label values X3ASMTMM V0959_;
   label values X4ASMTMM V0959_;
   label values X5ASMTMM V0959_;
   label values X1ASMTYY V0960_;
   label values X2ASMTYY V0961_;
   label values X3ASMTYY V0962_;
   label values X4ASMTYY V0963_;
   label values X5ASMTYY V0974_;
   label values X5STWCP V0985_;
   label values XKSTATUS V0986_;
   label values XKWHENK V0987_;
   label values XKKDATA V0988_;
   label values X5RPTR V0989_;
   
   
/************************
SAVE DATA IN STATA FORMAT
*************************/  
save "${data_directory}v01_eclsb.dta", replace ;

log close ;
